### ISSUE TITLE
Access-Control-Allow-Origin wrong value in case of not authorized Origin

### ISSUE THREAD

**Issue by zekth** [fastify/fastify-cors#127]
## 🐛 Bug Report

In the case of a non validated request the `Access-Control-Allow-Origin` is set to `false` as mentionned in https://github.com/fastify/fastify-cors/issues/124 . Which is not RFC compliant, also the use of `null` is not the best as said in https://w3c.github.io/webappsec-cors-for-developers/#avoid-returning-access-control-allow-origin-null . Would be better to not return the CORS header in the case a non validation. What do you think @mcollina ?

RFC: https://tools.ietf.org/html/rfc6454#section-7.1

**Comment by mcollina** [comment]
Let's go with it! PR?

**Comment by zekth** [comment]
I'll work on it
