### ISSUE TITLE
异步配置cors的 README 示例代码错误，容易误导使用者。

### ISSUE THREAD

**Issue by wangjie-mg** [fastify/fastify-cors#129]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

6.0.0

### Node.js version

14.16.1

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

11.2.3

## 问题一 :  README 示例代码有错误， `{ }` 不能作为return 的功能使用，应该使用`( )`  

![image](https://user-images.githubusercontent.com/55659214/117275207-618baf00-ae90-11eb-8a16-2aa6d037e5d5.png)

## 一些小建议：
源码中异步配置CORS是这样写的。
![image](https://user-images.githubusercontent.com/55659214/117275698-e2e34180-ae90-11eb-819e-af00b509aa2b.png)
- 其中分一个参数的情况和两个参数的情况，但是两种情况的入参一种是req，一种是reply，虽然没有错误，但是对于使用者来说不看源码的话，还是会有一些疑问
- 当我们使用一个参数的时候需要这样写，返回一个promise，这样是否有些多余，我们可以直接返回一个options，这样应该更加简洁和方便。
```
fastify.register(require('fastify-cors'), (instance) => { (req) => {
  let corsOptions;
  if (/localhost/.test(origin)) {
    corsOptions = { origin: false }
  } else {
    corsOptions = { origin: true }
  }
  return new Promise((resolve,reject)=>{
     resolve(corsOptions)
  })
 }
})
```
- 综上所述，我们像这样写，考虑放弃第二个参数 callback，可能会更加友好。
```
function handleCorsOptionsDelegator (optionsResolver, fastify) {
  fastify.addHook('onRequest', (req, reply, next) => {
    const options = optionsResolver(req,reply) 
    if(typeof options === 'object'){
      const corsOptions = Object.assign({}, defaultOptions, options)
      onRequest(fastify, corsOptions, req, reply, next)
    }else{
      next(new Error('Invalid CORS origin option'))
    }
    next()
  })
}
```
- 我们使用的时候只用返回一个options就好
```
fastify.register(require('fastify-cors'), (req, reply) => {
    //Other operations
    return { origin: '*', methods: 'POST' }
  })
```

上述如果有错误，我们可以一起讨论。

### Steps to Reproduce

-

**Comment by mcollina** [comment]
Unfortunately we do not understand Chinese :(.

**Comment by mcollina** [comment]
From google translate... if you can send a PR to fix the README that would be perfect.

**Comment by wangjie-mg** [comment]
> 不幸的是我们不懂中文:(。

My little suggestion is whether to consider using this method to deal with options
```
function handleCorsOptionsDelegator (optionsResolver, fastify) {
  fastify.addHook('onRequest', (req, reply, next) => {
    const options = optionsResolver(req,reply) 
    if(typeof options === 'object'){
      const corsOptions = Object.assign({}, defaultOptions, options)
      onRequest(fastify, corsOptions, req, reply, next)
    }else{
      next(new Error('Invalid CORS origin option'))
    }
    next()
  })
}
```
It’s more concise when we use it like this
```
fastify.register(require('fastify-cors'), (req, reply) => {
    //Other operations
    return { origin: '*', methods: 'POST' }
  })
```

**Comment by wangjie-mg** [comment]
> From google translate... if you can send a PR to fix the README that would be perfect.

This is a small problem. It seems that I don't have permission to the warehouse and it is more troublesome to apply for permission. I am a student. So I look forward to future cooperation

**Comment by climba03003** [comment]
> 
> 
> > 不幸的是我们不懂中文:(。
> 
> My little suggestion is whether to consider using this method to deal with options
> 
> ```
> function handleCorsOptionsDelegator (optionsResolver, fastify) {
>   fastify.addHook('onRequest', (req, reply, next) => {
>     const options = optionsResolver(req,reply) 
>     if(typeof options === 'object'){
>       const corsOptions = Object.assign({}, defaultOptions, options)
>       onRequest(fastify, corsOptions, req, reply, next)
>     }else{
>       next(new Error('Invalid CORS origin option'))
>     }
>     next()
>   })
> }
> ```
> 
> It’s more concise when we use it like this
> 
> ```
> fastify.register(require('fastify-cors'), (req, reply) => {
>     //Other operations
>     return { origin: '*', methods: 'POST' }
>   })
> ```

It should be a bug that we pass different things into the a single parameter. The function signature should be
`(req) => options`
`(req, options) => options`

**Comment by wangjie-mg** [comment]
> > > 不幸的是我们不懂中文:(。
> > 
> > 
> > My little suggestion is whether to consider using this method to deal with options
> > ```
> > function handleCorsOptionsDelegator (optionsResolver, fastify) {
> >   fastify.addHook('onRequest', (req, reply, next) => {
> >     const options = optionsResolver(req,reply) 
> >     if(typeof options === 'object'){
> >       const corsOptions = Object.assign({}, defaultOptions, options)
> >       onRequest(fastify, corsOptions, req, reply, next)
> >     }else{
> >       next(new Error('Invalid CORS origin option'))
> >     }
> >     next()
> >   })
> > }
> > ```
> > 
> > 
> > It’s more concise when we use it like this
> > ```
> > fastify.register(require('fastify-cors'), (req, reply) => {
> >     //Other operations
> >     return { origin: '*', methods: 'POST' }
> >   })
> > ```
> 
> It should be a bug that we pass different things into the a single parameter. The function signature should be either `async (req) => Promise<options>` or `(req, callback) => options`

This design is also good 。 about `async (req) => Promise<options>`  I have a small question, what are the specific benefits of using promise as the return value?

**Comment by climba03003** [comment]
> > > > 不幸的是我们不懂中文:(。
> > > 
> > > 
> > > My little suggestion is whether to consider using this method to deal with options
> > > ```
> > > function handleCorsOptionsDelegator (optionsResolver, fastify) {
> > >   fastify.addHook('onRequest', (req, reply, next) => {
> > >     const options = optionsResolver(req,reply) 
> > >     if(typeof options === 'object'){
> > >       const corsOptions = Object.assign({}, defaultOptions, options)
> > >       onRequest(fastify, corsOptions, req, reply, next)
> > >     }else{
> > >       next(new Error('Invalid CORS origin option'))
> > >     }
> > >     next()
> > >   })
> > > }
> > > ```
> > > 
> > > 
> > > It’s more concise when we use it like this
> > > ```
> > > fastify.register(require('fastify-cors'), (req, reply) => {
> > >     //Other operations
> > >     return { origin: '*', methods: 'POST' }
> > >   })
> > > ```
> > 
> > It should be a bug that we pass different things into the a single parameter. The function signature should be either `async (req) => Promise<options>` or `(req, callback) => options`
> 
> This design is also good 。 about `async (req) => Promise<options>`  I have a small question, what are the specific benefits of using promise as the return value?

async function always return Promise.

**Comment by wangjie-mg** [comment]
> > > > > 不幸的是我们不懂中文:(。
> > > > 
> > > > 
> > > > My little suggestion is whether to consider using this method to deal with options
> > > > ```
> > > > function handleCorsOptionsDelegator (optionsResolver, fastify) {
> > > >   fastify.addHook('onRequest', (req, reply, next) => {
> > > >     const options = optionsResolver(req,reply) 
> > > >     if(typeof options === 'object'){
> > > >       const corsOptions = Object.assign({}, defaultOptions, options)
> > > >       onRequest(fastify, corsOptions, req, reply, next)
> > > >     }else{
> > > >       next(new Error('Invalid CORS origin option'))
> > > >     }
> > > >     next()
> > > >   })
> > > > }
> > > > ```
> > > > 
> > > > 
> > > > It’s more concise when we use it like this
> > > > ```
> > > > fastify.register(require('fastify-cors'), (req, reply) => {
> > > >     //Other operations
> > > >     return { origin: '*', methods: 'POST' }
> > > >   })
> > > > ```
> > > 
> > > 
> > > It should be a bug that we pass different things into the a single parameter. The function signature should be either `async (req) => Promise<options>` or `(req, callback) => options`
> > 
> > 
> > This design is also good 。 about `async (req) => Promise<options>`  I have a small question, what are the specific benefits of using promise as the return value?
> 
> async function always return Promise.

Ok， i learned。
