### ISSUE TITLE
asynchronous dynamic cors not even worked!

### ISSUE THREAD

**Issue by tngflx** [fastify/fastify-cors#137]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

latest

### Plugin version

latest

### Node.js version

14

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

win10

### Description

yo your origin is pointing to nothing. How to fix this? I know it suppose to be an object?

### Steps to Reproduce

```
fastify.register(require('fastify-cors'), (instance) => (req, callback) => {
  let corsOptions;
  // do not include CORS headers for requests from localhost
  if (/localhost/.test(origin)) {
    corsOptions = { origin: false }
  } else {
    corsOptions = { origin: true }
  }
  callback(null, corsOptions) // callback expects two parameters: error and options
})

fastify.get('/', (req, reply) => {
  reply.send({ hello: 'world' })
})
```

.test(origin) points to undefined man

### Expected Behavior

origin should not be undefined

**Comment by zekth** [comment]
Indeed documentation is off. 
The code snippet should be something like this:
```js
fastify.register(require('fastify-cors'), (instance) => (req, callback) => {
  let corsOptions;
  // do not include CORS headers for requests from localhost
  if (/localhost/.test(req.getHeader(origin))) {
    corsOptions = { origin: false }
  } else {
    corsOptions = { origin: true }
  }
  callback(null, corsOptions) // callback expects two parameters: error and options
})

fastify.get('/', (req, reply) => {
  reply.send({ hello: 'world' })
})
```

Which is still confusing. See this test for more explicit use case: https://github.com/fastify/fastify-cors/blob/05419b05493138a07255545976fad1d5087cb9c9/test/cors.test.js#L184-L276

**Comment by tngflx** [comment]
Ok found a solution :

```
fastify.register(require('fastify-cors'), (instance) => async (req, callback) => {
    let corsOptions = {
        credentials: true,
        allowedHeaders: ["Origin, X-Requested-With, Content-Type, Accept"],
        origin: false
    }
    // do not include CORS headers for requests from localhost
    let originHostname = req.headers.origin || req.ip || '';
    if (/(localhost|ngrok|127.0.0.1)/g.test(originHostname)) {
        corsOptions.origin = true
    } else {
        corsOptions.origin = false
    }
    callback(null, corsOptions) // callback expects two parameters: error and options
})
```
This can dynamically match all kind of origin and assign cors for each route. its working so far.

**Comment by Sikora00** [comment]
I was sorry when I saw it 😟
