### ISSUE TITLE
Getting a OPTIONS under default tag in swagger doc

### ISSUE THREAD

**Issue by pradip-interra** [fastify/fastify-cors#143]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

3.19.0

### Plugin version

6.0,1

### Node.js version

14.17.0

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

10

### Description

I am facing an weird issue. In my swagger doc, I am always seeing  default OPTIONS API is getting listed without any specification from my routes. 

I am registering fastify-cors which seems the issue. 

```
fastify.register(require('fastify-cors'), {});
fastify.register(require('./routes/routes'));
```

This is the screen shot:

[![enter image description here][1]][1]

My versions are:

```
    "fastify": "^3.19.0",
    "fastify-auth0-verify": "^0.5.2",
    "fastify-cors": "^6.0.1",
    "fastify-swagger": "^4.8.2",
    "fastify-mongodb": "^2.0.1",
	"mongo-sanitize": "^1.1.0"
```

  [1]: https://i.stack.imgur.com/CmDYK.png

What's the way out? It looks really odd as my swagger is going to be out for our customers/integrators.

Thanks,
Pradip

### Steps to Reproduce

Use the versions and register it like 
```
fastify.register(require('fastify-cors'), {});
```

### Expected Behavior

The default route specification should not come in the swagger.

**Comment by mcollina** [comment]
Can you try

1. use v6.0.0
2. set the hideOptionsRoute flag to true 

Also, could you include a full example to reproduce?

Thanks

**Comment by mcollina** [comment]
Should be fixed byb https://github.com/fastify/fastify-cors/pull/142
