### ISSUE TITLE
Typescript Support: Origin is undefined 

### ISSUE THREAD

**Issue by bkawk** [fastify/fastify-cors#154]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.0.0

### Plugin version

3.0.0

### Node.js version

v14.15.4

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

11.5.2

### Description

Following the async [example](https://github.com/fastify/fastify-cors#configuring-cors-asynchronously) in a typescript environment with fastify plugin results in origin is undefined

### Steps to Reproduce

Trying to set up CORS for fastify vai the fastify-plugin in a fairly strict typescript environment. The docs showing the async configuration https://github.com/fastify/fastify-cors#configuring-cors-asynchronously

```
import fp from 'fastify-plugin';
import cors from 'fastify-cors';

export default fp(async (fastify) => {
  fastify.register(cors, () => (callback: any): void => {
    let corsOptions;
    if (/localhost/.test(origin)) {
      corsOptions = { origin: false };
    } else {
      corsOptions = { origin: 'www.mywebsite.com' };
    }
    callback(null, corsOptions);
  });
});
```
The error I get is 
```
'origin' is not defined.eslintno-undef
Cannot find name 'origin'.ts(2304)
```
How do I define origin?

If I try the non-async example from the docs origin is still undefined 

```
import fp from 'fastify-plugin';
import cors from 'fastify-cors';

export default fp(async (fastify) => {
  fastify.register(cors, {
    origin: (origin, callback) => {
      // eslint-disable-next-line no-console
      console.log(origin); //<======== undefined
      if (/localhost/.test(origin)) {
        callback(null, true);
      } else {
        callback(new Error('Not allowed by CORS'), false);
      }
    },
  });
});
```

### Expected Behavior

I expect typescript to not complain about origin being undefined

Demo code can be found here https://github.com/bkawk/fastify-swagger/blob/cors/src/plugins/cors.ts

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by bkawk** [comment]
> Would you like to send a Pull Request to address this issue? Remember to add unit tests.
Unfortunately, this issue goes beyond my understanding, otherwise I'd love to help out

**Comment by damey2011** [comment]
This still happens with Fastify 4 and Fastify CORS 8.1.0

**Comment by Eomm** [comment]
Please open a new detailed issue adding a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).
