### ISSUE TITLE
Update `latest` tags on the NPM registry

### ISSUE THREAD

**Issue by mgrenier** [fastify/fastify-cors#17]
I was a bit confused by the deprecation of @types/fastify-cors. The deprecation message is telling that the latest fastify-cors has its own type definition. But `latest` is still pointing to `1.0.0` which hasnt any type definition.

```
> npm info fastify-cors versions
[ '0.0.1',
  '0.1.0',
  '0.2.0',
  '1.0.0',
  '2.0.0',
  '2.0.1',
  '2.1.0',
  '2.1.1' ]

> npm info fastify-cors dist-tags
{ latest: '1.0.0', next: '2.0.1' }
```

**Comment by cemremengu** [comment]
Version 2.x of this plugin supports only Fastify 2.x which will be released soon (currently RC) and the `next` tag will the new `latest`. Sorry for the confusion with the wording there.

**Comment by Extarys** [comment]
Should update those tags now, Fastify 2.0 officially landed :rocket:

**Comment by cemremengu** [comment]
@mcollina should I for all ?

**Comment by mcollina** [comment]
Fixed for this one.

@cemremengu if there are other, please do the honors. Thanks! If you have a list, please put it on an issue somewhere so we process it collectively.
