### ISSUE TITLE
Allow all headers with wildcard

### ISSUE THREAD

**Issue by rickerp** [fastify/fastify-cors#183]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Is is possible to allow all headers? I've tried it by passing a wildcard `*` to the `allowedHeaders` config option, and it didn't work. 
I think it would be a great addition to allow it, there are other libraries which allow it, for example, [fastapi](https://fastapi.tiangolo.com/tutorial/cors/#use-corsmiddleware)

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.
