### ISSUE TITLE
Weird issue with async registering the plugin breaking the route table

### ISSUE THREAD

**Issue by pvanagtmaal** [fastify/fastify-cors#189]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.27.2

### Plugin version

6.0.3

### Node.js version

16.14.0

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

21.10

### Description

Note: happens on MacOS as well

When registering the plugin in an async fashion, the fastify server's configuration is altered somehow in that `routePrefix`es remain set on the instance even without nested routes. Weirdly enough, this doesn't happen when calling `then` after registering the plugin.

See [this repo](https://github.com/pvanagtmaal/fastify-test)

The **ONLY** difference between the working and broken code:
```
$ diff broken.js working.js
11c11
<   })
---
>   }).then(() => console.log('cors registered'))
```

For reference, both tables:

```
// working.js
└── /
    ├── /
    ├── * (OPTIONS)
    └── v
        ├── 1/user (GET)
        └── 2/user (GET)

// broken.js
└── /
    ├── /
    ├── * (OPTIONS)
    └── v1/
        ├── user (GET)
        └── v2/user (GET)
```

### Steps to Reproduce

See [this repo](https://github.com/pvanagtmaal/fastify-test)

NOTE: code taken from the fastify [route example with prefixing](https://www.fastify.io/docs/latest/Reference/Routes/#route-prefixing)

* `npm install`
* `node working.js`
* `node broken.js`
* compare route table logs

### Expected Behavior

Expected both route tables to look like this:

```
└── /
    ├── /
    ├── * (OPTIONS)
    └── v
        ├── 1/user (GET)
        └── 2/user (GET)
```

**Comment by mcollina** [comment]
Transfering this to Fastify as it's a fastify bug

**Comment by climba03003** [comment]
@chrskrchr @mcollina 
I think the latest `avvio` have some unexpected side effect to the `fastify` registration flow.

I have tested against `avvio@7.2.2`, it works normally.

**Comment by mcollina** [comment]
Yes I figured as much

**Comment by mcollina** [comment]
The changed has been revert, thanks for reporting.

**Comment by pvanagtmaal** [comment]
Fix confirmed, thanks for looking into it so quickly!
