### ISSUE TITLE
Package renamed without updating readme

### ISSUE THREAD

**Issue by AWare** [fastify/fastify-cors#198]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

The package has been renamed to `@fastify/cors`, yet the readme refers to the old name. 
https://github.com/fastify/fastify-cors/pull/195

**Comment by Fdawgs** [comment]
See the Work To Be Done section in https://github.com/fastify/fastify/issues/3733#issuecomment-1111188683
