### ISSUE TITLE
Transferring from fastify-cors to @fastify/cors with no error output

### ISSUE THREAD

**Issue by naknode** [fastify/fastify-cors#210]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the regression has not already been reported

### Last working version

6.1.0

### Stopped working in version

8.0.0

### Node.js version

18.3.0

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Fedora 35

### 💥 Regression Report

The regression is that the plugin does not get registered in the fastify environment.

Here is a working example. 

```typescript
import { IncomingMessage, Server, ServerResponse } from "http";
import { fastify, FastifyInstance } from "fastify";
import fastifyCors from "fastify-cors";
import fastifyWebsocket from "@fastify/websocket";
import WebsocketEx from "./types/websocket";

export default class Game {
  public host: FastifyInstance<Server, IncomingMessage, ServerResponse>;

  constructor() {
    this.host = fastify();
  }

  public init = async (): Promise<void> => {
    this.host.register(fastifyCors, { origin: true, credentials: true });
    this.host.register(fastifyWebsocket);

    try {
      const PORT = process.env.PORT || 1250;
      await this.host.listen(PORT).then((address) => {
        console.log(`Fastify server connected at ${address}`);
      });
    } catch (err) {
      this.host.log.error(err);
      process.exit();
    }
  };
}
```

And here's the new one:

```typescript
import { IncomingMessage, Server, ServerResponse } from "http";
import { fastify, FastifyInstance } from "fastify";
import fastifyWebsocket from "@fastify/websocket";
import WebsocketEx from "./types/websocket";

export default class Game {
  public host: FastifyInstance<Server, IncomingMessage, ServerResponse>;

  constructor() {
    this.host = fastify();
  }

  public init = async (): Promise<void> => {
    this.host.register(require('@fastify/cors'), { origin: true, credentials: true });
    this.host.register(fastifyWebsocket);

    try {
      const PORT = process.env.PORT || 1250;
      await this.host.listen(PORT).then((address) => {
        console.log(`Fastify server connected at ${address}`);
      });
    } catch (err) {
      this.host.log.error(err);
      process.exit();
    }
  };
}
```

All I did was change it to this line: `this.host.register(require('@fastify/cors'), { origin: true, credentials: true });` and it stopped working.

### Steps to Reproduce

1. Uninstall `fastify-cors`
2. Install `@fastify/cors`
3. Update `fastify.register()` line
4. Run

### Expected Behavior

For it to run `await this.host.listen(PORT).then((address) => {` and run the server.

**Comment by mcollina** [comment]
What do you mean it stops working? Does it exists with an error?

**Comment by jsumners** [comment]
What is the version of the plugin? What version of Fastify are you using?

**Comment by naknode** [comment]
@mcollina @jsumners Thank you. I see that I had to update to Fastify v4. It's working now. I was on version 3. Now I have to figure out why my server keeps hitting `this.host.get("/", { websocket: true }, (connection) => {}` over and over. Ah the joys...
