### ISSUE TITLE
Example in read me does not work at all

### ISSUE THREAD

**Issue by jacob-orbiit** [fastify/fastify-cors#215]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.3.0

### Plugin version

8.0.0

### Node.js version

18.7.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12.4

### Description

The plugin does literally nothing. The response is not decorated and the plugin seems to have not even run.

### Steps to Reproduce

```js
import Fastify from 'fastify';
import cors from '@fastify/cors';
import middie from '@fastify/middie';

const fastify = Fastify();

await fastify.register(middie);
await fastify.register(cors);
```

I also tried [the example](https://www.fastify.io/docs/latest/Reference/Middleware/) from fastify.io, and that crashes immediately:

```js
await fastify.register(middie);
fastify.use(cors());
```

```console
[…]/@fastify/cors/index.js:20
  fastify.decorateRequest('corsPreflightEnabled', false)
          ^
TypeError: Cannot read properties of undefined (reading 'decorateRequest')
```

**Comment by mcollina** [comment]
Good post! We have not updated the README.

This should work:

```js
import fastify from fastify'
import cors from '@fastify/cors'

await fastify.register(cors, { 
  // put your options here
})

fastify.get('/', (req, reply) => {
  reply.send({ hello: 'world' })
})

await fastify.listen(3000)
```

I think you are confusing two things, this module and https://www.npmjs.com/package/cors.
You need middie only to use the cors middleware; otherwise, you can just use this plugin.

**Comment by jacob-orbiit** [comment]
Thanks for the response!

Sorry, when you say `fastify.register(cors, {})`, to which which `fastify` are you referring—the library or the instance? (naming them the same in the docs is **extremely** confusing).

**Comment by mcollina** [comment]
I'm sorry but I don't see where the confusion is with `require('cors')` vs `require('@fastify/cors)`. They are clearly two different modules.

**Comment by jacob-orbiit** [comment]
I'm not talking about `cors` vs `fastify/cors` (although that was also quite confusing). I'm talking about `fastify.register()`. What is `fastify` there? Is it the default factory export of this library or the instance created by that factory?

**Comment by mcollina** [comment]
Good spot! I've updated the example.

**Comment by jacob-orbiit** [comment]
Thanks! That ambiguity exists thorough the entire fastify docs btw.

The new/updated example you posted is exactly what I tried, and it didn't work (unless `middie` is interfering?).
