### ISSUE TITLE
FastifyError [Error]: fastify-plugin: fastify-cors - expected '3.x' fastify version, '4.4.0' is installed

### ISSUE THREAD

**Issue by coffeebeantraining** [fastify/fastify-cors#219]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4,4,0

### Plugin version

3.x

### Node.js version

v18.7.0

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Ubuntu 22.04

### Description

I get the following error when trying to use fastify/cors

(node:26409) [FST_MODULE_DEP_FASTIFY-CORS] FastifyWarning.fastify-cors: fastify-cors has been deprecated. Use @fastify/cors@7.0.0 instead. (Use `node --trace-warnings ...` to show where the warning was created) FastifyError [Error]: fastify-plugin: fastify-cors - expected '3.x' fastify version, '4.4.0' is installed     at Object.checkVersion (/home/markjones/workspace/mock-srv/node_modules/fastify/lib/pluginUtils.js:118:11)     at Object.registerPlugin (/home/markjones/workspace/mock-srv/node_modules/fastify/lib/pluginUtils.js:133:16)     at Boot.override (/home/markjones/workspace/mock-srv/node_modules/fastify/lib/pluginOverride.js:28:57)     at Plugin.exec (/home/markjones/workspace/mock-srv/node_modules/avvio/plugin.js:79:33)     at Boot.loadPlugin (/home/markjones/workspace/mock-srv/node_modules/avvio/plugin.js:272:10)     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {   code: 'FST_ERR_PLUGIN_VERSION_MISMATCH',   statusCode: 500
} 

Here is my app.js file:
'use strict'
const path = require('path')
const AutoLoad = require('@fastify/autoload')
const cors = require('@fastify/cors')

module.exports = async function (fastify, opts) {

  // Place here your custom code!
  fastify.register(cors)

  // Do not touch the following lines
  // This loads all plugins defined in plugins
  // those should be support plugins that are reused
  // through your application

  fastify.register(AutoLoad, {
    dir: path.join(__dirname, 'plugins'),
    options: Object.assign({}, opts)
  })

  // This loads all plugins defined in routes
  // define your routes in one of these
  fastify.register(AutoLoad, {
    dir: path.join(__dirname, 'routes'),
    options: Object.assign({}, opts)
  })
}

### Steps to Reproduce

npm init fastify -- --integrate
npm install
npm run dev

> mock-srv@1.0.0 dev 
> fastify start -w -l info -P app.js 

(node:26409) [FST_MODULE_DEP_FASTIFY-CORS] FastifyWarning.fastify-cors: fastify-cors has been deprecated. Use @fastify/cors@7.0.0 instead. (Use `node --trace-warnings ...` to show where the warning was created) FastifyError [Error]: fastify-plugin: fastify-cors - expected '3.x' fastify version, '4.4.0' is installed     at Object.checkVersion (/home/markjones/workspace/mock-srv/node_modules/fastify/lib/pluginUtils.js:118:11)     at Object.registerPlugin (/home/markjones/workspace/mock-srv/node_modules/fastify/lib/pluginUtils.js:133:16)     at Boot.override (/home/markjones/workspace/mock-srv/node_modules/fastify/lib/pluginOverride.js:28:57)     at Plugin.exec (/home/markjones/workspace/mock-srv/node_modules/avvio/plugin.js:79:33)     at Boot.loadPlugin (/home/markjones/workspace/mock-srv/node_modules/avvio/plugin.js:272:10)     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {   code: 'FST_ERR_PLUGIN_VERSION_MISMATCH',   statusCode: 500
} 

### Expected Behavior

Server listening at http//localhost:3000

**Comment by Uzlopak** [comment]
Well use latest @fastify/cors

**Comment by coffeebeantraining** [comment]
Are there any references for how to use the latest @fastify/cors ?
I was assuming that executing this command: npm init fastify -- --integrate
would install the latest, but apparently not.

**Comment by Uzlopak** [comment]
i run now  `npm init fastfy -- --integrate` and it did not install @fastify/cors nor fastify-cors.

**Comment by coffeebeantraining** [comment]
did you mean fastify?  i see your command line is missing the "i" in fastify for: npm init fastify -- --integrate
when i ran that command line the following entries were created for package.json
`{
  "name": "mock-srv",
  "version": "1.0.0",
  "description": "This project was bootstrapped with Fastify-CLI.",
  "main": "app.js",
  "directories": {
    "test": "test"
  },
  "scripts": {
    "test": "tap \"test/**/*.test.js\"",
    "start": "fastify start -l info app.js",
    "dev": "fastify start -w -l info -P app.js"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@fastify/autoload": "^5.0.0",
    "@fastify/cors": "^7.0.0",
    "@fastify/sensible": "^4.1.0",
    "fastify": "^4.0.0",
    "fastify-cli": "^4.4.0",
    "fastify-cors": "^6.1.0",
    "fastify-plugin": "^3.0.0"
  },
  "devDependencies": {
    "tap": "^16.1.0"
  }
}
`

**Comment by coffeebeantraining** [comment]
can you try these commands:
**npm init fastify -- --integrate
npm install
npm run dev**

**Comment by climba03003** [comment]
Please use `@fastify/cors`.

**Comment by coffeebeantraining** [comment]
> Please use `@fastify/cors`.

Thank you, 
worked using @fastify/cors with small tweaks.
out of the box, npm init fastify creates an app.js file and the documentation does not
explain clearly how to enable cors support after the app.js file is created using npm init fastify.


npm init fastify
npm install
npm i @fastify/cors
npm run dev

/////////////////////////////////
//app.js created from executing npm init fastify
/////////////////////////////////
'use strict'

const path = require('path')
const AutoLoad = require('@fastify/autoload')

///////////////////////////////////////////////////////////////////
//Added per link: https://github.com/fastify/fastify-cors
const cors = require('@fastify/cors')
///////////////////////////////////////////////////////////////////

module.exports = async function (fastify, opts) {

  // Place here your custom code!
  //////////////////////////////////////////////////////////////////////
  //Added per link: https://github.com/fastify/fastify-cors
  //removed "await" prefixed in front of fastify.register(cors,{})
  /////////////////////////////////////////////////////////////////////
  fastify.register(cors, { 
    // put your options here
  })

  // Do not touch the following lines

  // This loads all plugins defined in plugins
  // those should be support plugins that are reused
  // through your application
  fastify.register(AutoLoad, {
    dir: path.join(__dirname, 'plugins'),
    options: Object.assign({}, opts)
  })

  // This loads all plugins defined in routes
  // define your routes in one of these
  fastify.register(AutoLoad, {
    dir: path.join(__dirname, 'routes'),
    options: Object.assign({}, opts)
  })
}
