### ISSUE TITLE
convert fastify-cors to @fastify/cors

### ISSUE THREAD

**Issue by MoJassor** [fastify/fastify-cors#220]
### Prerequisites

- [X] I have searched existing issues to ensure the bug has not already been reported

- [X] I have written a descriptive issue title

### Fastify version

4.5.3

### Plugin version

7.0.0

### Node.js version

16.13.0

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

20.04

### Description

I convert fastify-cors Plugin to @fastify/cors, then I've this error message "**fastify-plugin: fastify-cors - expected '3.x' fastify version, '4.5.3' is installed**"

### Steps to Reproduce

const CORS = require("@fastify/cors");
const app = Fastify(opts);
app.register(CORS, {
     origin: true,
    methods: ["OPTIONS", "PUT", "GET", "POST", "DELETE"],
    allowedHeaders: ["Content-Type", "Authorization"],
  });

### Expected Behavior

Server listening at 3001

**Comment by Uzlopak** [comment]
You should use latest @fastify/cors.
