### ISSUE TITLE
doesnt' work with Typescript

### ISSUE THREAD

**Issue by xtianus79** [fastify/fastify-cors#226]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3

### Plugin version

8

### Node.js version

16

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

22

### Description

First. What is this?

```
???await??? fastify.register(cors, { 
  // put your options here
})
```

There is nothing async referencing it. It throws a type error. 

Secondly without the await and how I have it setup which is like the example it doesn't do anything. 

### Steps to Reproduce

install fastify
install typscript 

run code. 

### Expected Behavior

to work

**Comment by climba03003** [comment]
Your plugin version is wrong. You are using `fastify@3` and the plugin version should be `7.x`.

You need to provide a reproducible code snippet. `TypeScript` is complicated and it behave differently for each `tsconfig.json`.
