### ISSUE TITLE
Typescript definition misleading

### ISSUE THREAD

**Issue by diondirza** [fastify/fastify-cors#23]
Hey guys, I start using this plugin with TS support in my codebase, and I use a custom function for origin field for cors options. Which I found the sample for it in your test file here 

https://github.com/fastify/fastify-cors/blob/master/test/cors.test.js#L240.

But I got an error when using this kind of function signature, that TS told me about incompatible types for my function. When I look out on the d.ts file is supposed to be `originCallback` type

https://github.com/fastify/fastify-cors/blob/master/index.d.ts#L7

I think that type is for the second parameter in the function right? And the definition should be 

```
type originCustom = (header: string, cb: originCallback) => void;
....
origin?: string | boolean | RegExp | string[] | RegExp[] | originCustom; // not originCallback
```

am I correct here, or the test is misguided me?

**Comment by mcollina** [comment]
I think the tests win, so they types are going to be wrong. Would you like to send a PR?

**Comment by diondirza** [comment]
Sure man, PR submitted. 🚀

**Comment by diondirza** [comment]
Thanks for landing the fix, this issue should be closed now
