### ISSUE TITLE
Latency when using a large JWT token

### ISSUE THREAD

**Issue by anderseklof** [fastify/fastify-cors#238]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.10.2

### Plugin version

8.2.0

### Node.js version

16.15.1

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Windows 10 with WSL Ubuntu 20.04

### Description

When using a large JWT token (>1kB) in `Bearer`, the request gets an extra ~50 ms latency.

This happens only when doing a request from an web browser, i.e. using the `@fastify/cors` plugin in the server, and when the JWT token is larger than about 1kB.

I have tested the same setup with Express and their CORS middleware without any issues.

### Steps to Reproduce

I have created a repo to reproduce the problem: https://github.com/anderseklof/fastify-cors-latency. Instructions in the README.

### Expected Behavior

Expected behavior is that `@fastify/cors` should be able to handle large JWT tokens without any noticeable latency.

**Comment by mcollina** [comment]
Thanks for reporting!

Can you provide steps to reproduce? We often need a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.

**Comment by Uzlopak** [comment]
@kibertoad

**Comment by climba03003** [comment]
I believe the latency is about `pre-flight` for `CORS`.

I search a bit on `Express CORS` and it requires to explicitly set `.options` in order to handle the `pre-flight`. 
However, `fastify` be default provide `pre-flight` handling which means we always does one more route before the actual handler.

**Comment by anderseklof** [comment]
I have created a repo that reproduces the problem, see updated issue text.

**Comment by climba03003** [comment]
I cannot reproduce the problem. The below one is the graph from Firefox Devtools which give you above `OPTION` and `POST` return with 1ms under two button.
![image](https://user-images.githubusercontent.com/23028015/210169822-1dc5889c-b262-4efc-8fc3-857c35d85384.png)

**Comment by anderseklof** [comment]
As I could reproduce this problem in my setup using Windows and WSL (my daily development environment) I cloned the repo to my Windows environment, not using WSL. Running only in Windows I could not reproduce the problem, everything is working as expected.

While I tested some more I got an `400: Unexpected end of JSON input` while trying a JWT token that was exactly 3500 bytes. This happened both in Windows only and WSL scenario. Trying a token that was even larger (4kB), I got `200` again with no latency in Windows and latency in WSL.

Logs from `400`:

```
{
  "level": 30,
  "time": 1672583836064,
  "pid": 16113,
  "reqId": "req-19",
  "res": { "statusCode": 400 },
  "err": {
    "type": "SyntaxError",
    "message": "Expected ',' or ']' after array element in JSON at position 53",
    "stack": "SyntaxError: Expected ',' or ']' after array element in JSON at position 53\n    at JSON.parse (<anonymous>)\n    at Function.parse (/home/xxx/development/fastify-cors-latency/node_modules/secure-json-parse/index.js:26:20)\n    at Parser.defaultJsonParser [as fn] (/home/xxx/development/fastify-cors-latency/node_modules/fastify/lib/contentTypeParser.js:285:25)\n    at IncomingMessage.onEnd (/home/xxx/development/fastify-cors-latency/node_modules/fastify/lib/contentTypeParser.js:269:27)\n    at IncomingMessage.emit (node:events:513:28)\n    at endReadableNT (node:internal/streams/readable:1359:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)",
    "statusCode": 400
  },
  "msg": "Expected ',' or ']' after array element in JSON at position 53"
}
```

Scenarios tested:

```
1) JWT 1kB curl from Windows --> server in WSL : OK
2) JWT 1kB curl from WSL --> server in WSL : OK
3) JWT 500 bytes web request from Windows --> server in WSL : OK
4) JWT 1kB web request from Windows --> server in WSL : Latency 40-50 ms - visible in Fastify server logs
5) JWT 3,5kB web request from Windows --> server in WSL : status code `400`
6) JWT 4kB web request from Windows --> server in WSL : Latency 40-50 ms - visible in Fastify server logs
7) JWT 500 bytes web request from Windows --> server in Windows : OK
8) JWT 1kB web request from Windows --> server in Windows : OK
9) JWT 3,5kB web request from Windows --> server in Windows : status code `400`
10) JWT 4kB web request from Windows --> server in Windows : OK
```

Logs from scenario 4:

```
{"level":30,"time":1672582213151,"reqId":"req-4l","req":{"method":"OPTIONS","url":"/test-route","hostname":"127.0.0.1:2090","remoteAddress":"127.0.0.1","remotePort":42550},"msg":"incoming request"}
{"level":30,"time":1672582213151,"msg":"<<<<<<< onRequest"}
{"level":30,"time":1672582213151,"msg":"<<<<<<< onSend"}
{"level":30,"time":1672582213151,"msg":"<<<<<<< onResponse"}
{"level":30,"time":1672582213151,"reqId":"req-4l","res":{"statusCode":204},"responseTime":0.3050999641418457,"msg":"request completed"}
{"level":30,"time":1672582213154,"reqId":"req-4m","req":{"method":"POST","url":"/test-route","hostname":"127.0.0.1:2090","remoteAddress":"127.0.0.1","remotePort":42550},"msg":"incoming request"}
{"level":30,"time":1672582213154,"msg":"<<<<<<< onRequest"}
{"level":30,"time":1672582213154,"msg":"<<<<<<< preParsing"}
{"level":30,"time":1672582213203,"msg":"<<<<<<< preValidation"}
{"level":30,"time":1672582213203,"msg":"<<<<<<< preHandler"}
{"level":30,"time":1672582213203,"msg":"<<<<<<< handler"}
{"level":30,"time":1672582213203,"msg":"<<<<<<< preSerialization"}
{"level":30,"time":1672582213203,"msg":"<<<<<<< onSend"}
{"level":30,"time":1672582213203,"msg":"<<<<<<< onResponse"}
{"level":30,"time":1672582213203,"reqId":"req-4m","res":{"statusCode":200},"responseTime":49.63890099525452,"msg":"request completed"}
```

Something seams to be happening between `preParsing` and `preValidation` during CORS. What is causing this and why is it only happening for some requests? And why did I get an `400`, are there some request limits?

**Comment by climba03003** [comment]
From the log you provide, I would expect you are actually sending invalid JSON to the server. 
So, the problem is unrelated to `CORS`.

I recommend you to check what is the input you send.

**Comment by anderseklof** [comment]
Ok, I will investigate my WSL environment.

Thanks for your assistance.
