### ISSUE TITLE
Setting for `Cache-Control` to allow preflight requests to be cached in CDNs

### ISSUE THREAD

**Issue by brettwillis** [fastify/fastify-cors#251]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Add a `cacheContol` option to the settings which will set `Cache-Contol` header on preflight responses. 

A number value would probably set `Cache-Control: max-age=${cacheContol}`, and a string value would set `Cache-Control: ${cacheContol}` (fully sepecify the header contents), and otherwise the header would not be set.

### Motivation

There is a `maxAge` option for the `Access-Control-Max-Age` header. This typically allows preflight requests to be cached in the browser, however typically not by a CDN.

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.
