### ISSUE TITLE
Error(s) in doc.

### ISSUE THREAD

**Issue by GHNewbiee** [fastify/fastify-cors#253]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

> - hook: See the section Custom Fastify hook name (default: onResponse)

As per code:

```js
const defaultOptions = {
  origin: '*',
  methods: 'GET,HEAD,PUT,PATCH,POST,DELETE',
  hook: 'onRequest',
  preflightContinue: false,
  optionsSuccessStatus: 204,
  credentials: false,
  exposedHeaders: null,
  allowedHeaders: null,
  maxAge: null,
  preflight: true,
  strictPreflight: true
}
```

default is `onRequest`, isn't it? *Tia*

**Comment by Uzlopak** [comment]
provided PR #254
