### ISSUE TITLE
cacheControl default value is missing

### ISSUE THREAD

**Issue by GHNewbiee** [fastify/fastify-cors#255]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Doc does not mention the default value of `cacheControl`. Neither in code is given. So, is there a default value, and if yes, what is that? *Tia*

**Comment by Uzlopak** [comment]
There is no default value. So cacheControl is not set.
