### ISSUE TITLE
Access-Control-Allow-Origin is not working when streaming the data

### ISSUE THREAD

**Issue by iserioton** [fastify/fastify-cors#259]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

8.2.0

### Node.js version

18.16.1

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

Window 10

### Description

I set up the cors like this: `server.register(cors, {
		origin: '*',
	});
`

It works for normal APIs, but when I stream the data, it does not work. 
`const stream = fs.createReadStream(filePath);
				reply.type('application/json').header('Content-Length', fs.statSync(filePath).size);
				return stream.pipe(reply.raw);`

### Steps to Reproduce

Follow the description!

### Expected Behavior

It should set "Access-Control-Allow-Origin" to "*" for the response header!

**Comment by Uzlopak** [comment]
See the test i added to the PR #260 on how to do it correct.

**Comment by VityaSchel** [comment]
Any workaround?

**Comment by Uzlopak** [comment]
Why cant you use reply.send(stream)?

**Comment by mcollina** [comment]
`stream.pipe(reply.raw)` bypasses all Fastify logic by using `reply.raw`. Use `return stream` in your route or `reply.send(stream)`

**Comment by iserioton** [comment]
Also worked when I did this: 
```
reply
  .type("application/json")
  .header("Access-Control-Allow-Origin", "*")
  .header("Content-Length", fs.statSync(filePath).size);
reply.raw.writeHead(200, reply.getHeaders());
return stream.pipe(reply.raw);
```
