### ISSUE TITLE
AvvioError [Error]: Plugin did not start in time: '[object Promise]'

### ISSUE THREAD

**Issue by ykamal** [fastify/fastify-cors#263]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.13.0

### Plugin version

8.3.0

### Node.js version

18.2.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

13.4.1

### Description

Hi. I am using a NestJS application with fastify and trying to integrate fastify cors. This is the code:

```
const app = await NestFactory.create<NestFastifyApplication>(AppModule, new FastifyAdapter());
app.enableCors({ origin: '*' });
```

That throws this error:

```shell
AvvioError [Error]: Plugin did not start in time: '[object Promise]'. You may have forgotten to call 'done' function or to resolve a Promise
    at Timeout._onTimeout (/Users/yousof.kamal/Documents/Work/pps-routing-app/node_modules/avvio/plugin.js:122:19)
    at listOnTimeout (node:internal/timers:564:17)
    at processTimers (node:internal/timers:507:7) {
  code: 'AVV_ERR_READY_TIMEOUT',
  fn: <ref *1> [Function: fastifyCors] {
    default: [Circular *1],
    fastifyCors: [Circular *1],
    [Symbol(skip-override)]: true,
    [Symbol(fastify.display-name)]: '@fastify/cors',
    [Symbol(plugin-meta)]: { fastify: '4.x', name: '@fastify/cors' }
  }
}
``` 

### Steps to Reproduce

Steps to reproduce:

1. latest Nestjs
2. latest fastify
3. latest fastify-cors

in `main.ts` add this line:

```
const app = await NestFactory.create<NestFastifyApplication>(AppModule, new FastifyAdapter());
app.enableCors({ origin: '*' });
```

run the server with `npm run start:dev`

### Expected Behavior

It should enable cors as expected

**Comment by Eomm** [comment]
Could you add a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)?

Without it, we are unable to help you.

**Comment by mcollina** [comment]
Thanks for reporting. We do not have the resources to support Nest.js users. Please refer to the Nest [Discord](https://discord.gg/NestJS) channel (support) for such questions.
