### ISSUE TITLE
Missing type declaration file for ‘@fastify/cors’ module

### ISSUE THREAD

**Issue by ch4rliedev** [fastify/fastify-cors#280]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.24.3

### Plugin version

8.4.1

### Node.js version

20.10.0

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

23H2

### Description

Hello,

I’m using the @fastify/cors module in my JavaScript project and noticed that TypeScript is throwing a warning because it can’t find a type declaration file for this module.

The warning is as follows:

> Could not find a declaration file for module '@fastify/cors'. 'c:/Users/charl/OneDrive/Documentos/Programação/JavaScript/Boruto Raiden (fastify)/node_modules/@fastify/cors/index.js' implicitly has an 'any' type.ts(7016)

Although my project is in JavaScript, I’m using a code editor that supports TypeScript (like Visual Studio Code), and this warning shows up.

Would it be possible to add a type declaration file to the @fastify/cors module to resolve this warning?

### Steps to Reproduce

```
import cors from '@fastify/cors'

await fastify.register(cors, {
  origin: "https://site.com",
  credentials: true
});
```

### Expected Behavior

Upon resolving the issue, I would expect that TypeScript would no longer throw a warning when importing the `@fastify/cors` module in a JavaScript project. This would be achieved by including a type declaration file in the `@fastify/cors` module. As a result, TypeScript would be able to understand the types used in `@fastify/cors`, and developers would not see the warning in their code editors that support TypeScript. This would make the development experience smoother and more enjoyable.

that is my first issue, sorry

**Comment by Fdawgs** [comment]
I can't replicate using:
- Typescript 5.4.5
- VS Code 1.88.1
- Fastify 4.26.2
- Fastify/cors 9.0.1

![image](https://github.com/fastify/fastify-cors/assets/43814140/889af799-5f9a-4b7f-9b15-a2155df2b676)

Running `tsc` builds just fine as well.
