### ISSUE TITLE
Module Not Setting the Headers in the Response

### ISSUE THREAD

**Issue by mohammadazeemwani** [fastify/fastify-cors#314]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.28.1

### Plugin version

9.0.1

### Node.js version

20.8.1

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

10

### Description

the module is not setting the headers 
client is on: `http://localhost:5173`
api is on `http://localhost:4000`
browser: google chrome

### My Situation
my client side request is this
```javascript
      const response = await fetch(`${CONFIG.HOST}${CONFIG.SUPERUSER_LOGIN_ENDPOINT}`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ email, password }),
      });
      const data = await response.json();
      console.log('response logging:', data.success);
```

my CORS configuration is this:
```javascript
import cors from "@fastify/cors";

export default async function (fastify, opts) {
  const corsOptions = {
    origin: ["http://localhost:5173", "https://meekat.serveo.net"],
    credentials: true,
  };
  fastify.register(cors, corsOptions);
}
```

after all is setup properly, the error i am getting is this 
```
Access to fetch at 'http://localhost:4000/superuser-login' from origin 'http://localhost:5173' 
has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the 
requested resource. If an opaque response serves your needs, set the request's mode 
to 'no-cors' to fetch the resource with CORS disabled. 
```

### My Research 

so far I digged into the main module `@fastify/cors` in index.js 
the function which sets the header, I logged the headers there
```javascript
function addCorsHeaders (req, reply, originOption, corsOptions) {
  const origin = getAccessControlAllowOriginHeader(req.headers.origin, originOption)
  if (origin) {
    reply.header('Access-Control-Allow-Origin', origin)
    console.log('headers in module: ', reply.getHeaders())
  }
  ...rest-function
}
```
and also logged the headers just before sending the response:
```javascript
console.log('headers from route: ', reply.getHeaders());
if (check) {
    return reply.code(200).send({ success: true });
} else {
    return reply.code(401).send({ success: false });
}
```

and I got this: 
```js
headers in module:  {
  vary: 'Origin',
  'access-control-allow-origin': 'http://localhost:5173'
}
headers from route:  {}
```

so I think after the module is setting the headers something uninteded is causing this issue?

P.S: I have checked following strategies but none work
> - using regex for origin
> - using https 
> - clearing cache 

### Expected Behavior

I want the request to happen without any errors I am facing

**Comment by Eomm** [comment]
> so I think after the module is setting the headers something uninteded is causing this issue?

Yes, I think so.

Could you add a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)?

Without it, we are unable to help you.

**Comment by mohammadazeemwani** [comment]
@Eomm 

I made an MRE here [https://stackblitz.com/edit/stackblitz-starters-n6gvrf?file=index.html](https://stackblitz.com/edit/stackblitz-starters-n6gvrf?file=index.html)

***Instructions to use MRE***
simply run
`npm run start`

this will boot up two servers

1. api on port: 4000

   > [frontEndURL](https://stackblitzstartersn6gvrf-ftba--5173--af4c8d9c.local-credentialless.webcontainer.io/)

2. frontEnd on port: 5173
   > [apiEndpoint](https://stackblitzstartersn6gvrf-ftba--4000--af4c8d9c.local-credentialless.webcontainer.io/)

***Instruction End***

***

Along the way realised that it is the fastify/autoload that is doing the problem 
and by configuring fastifyCors before all plugins and fastify/autoload, it is working for now!

but for some reasons I don't know fastify/autoload is changing the headers after @fastify/cors is setting them

**Comment by mcollina** [comment]
In your example,

```js
await fastify.register(cors, corsOptions)
```

would fix it.

Take a look at our plugin system model and encapsulation in our docs.
