### ISSUE TITLE
Different allowed origins for different routes

### ISSUE THREAD

**Issue by bradenhs** [fastify/fastify-cors#33]
It would be nice to have a way to specify different allowed origins for different routes. For example, if I have a public api endpoint available to third parties it would be nice to specify in the plugin options `origin: "*"` for that and `origin: false` for other routes. I tried passing a function to the `origin` option but it looks like only `req.headers.origin` is passed into that instead of the entire request object. Is there a good pattern to satisfy this use case?

**Comment by Eomm** [comment]
You can do it already using the encapsulation context, it is not a route level, but I would better to split the context between public apis and private ones

```
const fastify = require('fastify')({ logger: true })

fastify.register((instance, opts, next) => {
  instance.register(require('fastify-cors'), {
    origin: 'http://example.com'
  })
  instance.get('/', (req, res) => { res.send('one') })
  next()
}, { prefix: 'one' })

fastify.register((instance, opts, next) => {
  instance.register(require('fastify-cors'), {
    origin: 'http://foobar.com'
  })
  instance.get('/', (req, res) => { res.send('two') })
  next()
}, { prefix: 'two' })

fastify.listen(3000)

// curl -v http://localhost:3000/one
// curl -v http://localhost:3000/two
```

**Comment by bradenhs** [comment]
I'm new to fastify so I appreciate the pointer! Thanks for the help.
