### ISSUE TITLE
Origin function does not receive `origin` attribute

### ISSUE THREAD

**Issue by niekfrontmen** [fastify/fastify-cors#4]
Hi,

First of all, good job guys!
I am looking at the possibilities of Fastify and the plugins and noticed that when using a function to validate the origin, it is not passed (always undefined).

fastify.register(require('fastify-cors'), {
    origin: (origin, callback) => {
      console.log('ORG: ', origin)

      const whitelist = [undefined]
      if (whitelist.indexOf(origin) !== -1) {
        callback(null, true)
      } else {
        callback(new Error('Not allowed by CORS'))
      }
    }
  })

**Comment by mcollina** [comment]
Good spot! Would you like to send a pull request to fix this?

**Comment by niekfrontmen** [comment]
Hey Mcollina,

Noob error on my end...had an extension on my end which resulted in no origins being sent to the server from the Browser.

Everything works great!

**Comment by dalisoft** [comment]
@niekfrontmen Can you tell me please which plug-in can cause this? For me this issue happens too

**Comment by Eomm** [comment]
If you need help, feel free to open a new issue with a clear example of what you want to accomplish and what you have done that is not working 👍
