### ISSUE TITLE
access-control-allow-origin always false

### ISSUE THREAD

**Issue by ardyfeb** [fastify/fastify-cors#48]
## 🐛 Bug Report

`access-control-allow-origin` always false and `access-control-allow-methods` not found on response headers

My configuration

```js
app.register(require('fastify-cors'), {
    origin: ['https://juabali.com'],
    methods: ['GET', 'POST, 'PUT', 'PATCH', 'DELETE'],
    allowedHeaders: [
      'Authorization',
      'Content-Type',
      'User-Agent',
      // user device headers
      'X-Device-Brand',
      'X-Device-Model',
      'X-Device-Platform',
      'X-Device-OS',
      'X-Device-Token',
      // client info headers
      'X-Client-AppVersion',
      'X-Client-AppId',
      'X-Client-Id',
    ],
    credentials: true,
  });
```

## Expected behavior

`access-control-allow-origin`to be same at configuration

Result

```bash
➜ http localhost:3000

HTTP/1.1 200 OK
Connection: keep-alive
Date: Sat, 07 Dec 2019 19:03:48 GMT
Strict-Transport-Security: max-age=15552000; includeSubDomains
X-Content-Type-Options: nosniff
X-DNS-Prefetch-Control: off
X-Download-Options: noopen
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
access-control-allow-credentials: true
access-control-allow-origin: false
content-length: 43
content-type: application/json; charset=utf-8
etag: "1i9popv"
vary: Origin

{
    "name": "Juabali Turtle",
    "version": "0.0.1"
}
```

## Your Environment

- *node version*: 10.15.2
- *fastify version*: 2.10.0
- *os*: Linux

**Comment by mcollina** [comment]
Would you like to send a fix/PR for this? It'd be very welcomed.

**Comment by Eomm** [comment]
The problem seems to be when an origin is not in the array:

https://github.com/fastify/fastify-cors/blob/1e37b0af70e6c534521834bc2b7b7c43eb9af127/index.js#L131

**Comment by fox1t** [comment]
@ardyfeb you need to add preflight in order to have `Access-Control-Allow-Methods` set. On the other hand, in order to have `access-control-allow-origin` added to the response, you need to serve from the domain and not from `localhost:3000` because of what @Eomm said.
Closing this for now.
