### ISSUE TITLE
Pass fastify instance to origin function

### ISSUE THREAD

**Issue by SkeLLLa** [fastify/fastify-cors#5]
Hi. In order to allow usage of previously registered modules and plugins (e.g. like fastify-mongo or others) in origin function it will be good if fastify instance will be passed there as parameter.

Now it's only an option to use closure for that, but that limits a bit where that function could be declared.

**Comment by mcollina** [comment]
Sure! Would you like to send a PR?

**Comment by SkeLLLa** [comment]
@mcollina Yes. But I want to know what's the best way to do that.

So in order to pass fastify instance one option is to add `fastify` param to origin call https://github.com/fastify/fastify-cors/blob/master/index.js#L98 and we'll receive
```js
var result = origin(reqOrigin, fastify, _onOrigin)
```
So it will be breaking change for those who use callbacks.

As an alternative we can try use `.call()` or `.apply()` call to bind fastify into `this` function context. However this option is not very nice IMO.

Probably if you have other ideas I'd implement those as well.

**Comment by mcollina** [comment]
I'm ok with the breaking change. This module is at version 0.1.0 (< 1.0.0).
