### ISSUE TITLE
How to use origin callback and pass null in TypeScript?

### ISSUE THREAD

**Issue by krisread** [fastify/fastify-cors#53]
In the exported types, the callback definition for the origin function is: 

```
type originCallback = (err: Error, allow: boolean) => void;

type originFunction = (origin: string, callback: originCallback) => void;
```

This does not allow us to call as follows (per examples?)

```
callback(null, true);
```

Note:  cannot pass null for the first parameter as it is not of type Error

How should we call the callback in case where there is no error?

**Comment by Eomm** [comment]
Should the originCallback be define as:

`type originCallback = (err?: Error, allow?: boolean) => void;`

Would you like to send a PR to fix it?

cc @Ethan-Arrowood

**Comment by krisread** [comment]
@Eomm @Ethan-Arrowood  

PR posted at

https://github.com/fastify/fastify-cors/pull/54

**Comment by migramcastillo** [comment]
New PR posted at #58 

However, if you came here for the same problem, a workaround that is currently working for me is declaring the callback as `Function` type:

```ts
fastify.register(fastifyCors, {
    methods: ["GET", "PUT", "POST", "DELETE"],
    origin: (origin: string, cb: Function) => {
       if(/localhost/.test(origin)){
             // It allows to use the null arg value
             cb(null, true);
             return;
       }
       // Throw error as well
       cb(new Error("Not allowed"), false);
    }
  });
```

**Comment by Eomm** [comment]
Released

Thks for the PR!
