### ISSUE TITLE
add CORS headers to non-preflight

### ISSUE THREAD

**Issue by tuanalumi** [fastify/fastify-cors#55]
## 🐛 Bug Report

The plugin does not add CORS headers to non-preflight requests, and Chrome does not accept this. In `cors` package, they do this.

## To Reproduce

In the source, I see that the headers are added only when request method is OPTIONS. 

## Expected behavior

Add CORS headers to requests whose method is not OPTIONS.

## Your Environment

- *node version*: 12
- *fastify version*: >=1.0.0
- *os*: Linux

**Comment by mcollina** [comment]
Can you please provide an example and how to reproduce? Thanks.

**Comment by tuanalumi** [comment]
**With express's `cors`**

There are 2 requests. The first one is preflight. In both requests, there are CORS headers.
![image](https://user-images.githubusercontent.com/5226413/73942912-7478a200-4922-11ea-81be-df20c9d1a5c4.png)

![image](https://user-images.githubusercontent.com/5226413/73942968-8a866280-4922-11ea-9a99-8587627cd8db.png)

![image](https://user-images.githubusercontent.com/5226413/73943008-9a9e4200-4922-11ea-8e54-f20b5b1a9085.png)

**With `fastify-cors`**

Second request does not have all CORS headers
![image](https://user-images.githubusercontent.com/5226413/73943841-1220a100-4924-11ea-8c18-8e36d92f430e.png)

Which causes Chrome to block the request:

> Access to XMLHttpRequest at 'https://localhost:892/users/login' from origin 'https://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by mcollina** [comment]
Would you mind to include an example code to reproduce this?

https://github.com/fastify/fastify-cors/blob/master/test/cors.test.js#L168-L221 should cover this case.

**Comment by tuanalumi** [comment]
This is my config for the plugin.

```
const origin = [`https://localhost:${process.env.PORT_WEB_APP}`];

server.register(require('fastify-cors'), {
  origin,
  credentials: true,
  allowedHeaders: [
    'Authorization',
    'Accept',
    'Origin',
    'DNT',
    'Keep-Alive',
    'User-Agent',
    'X-Requested-With',
    'If-Modified-Since',
    'Cache-Control',
    'Content-Type',
    'Content-Range',
    'Range',
  ],
  methods: 'GET,POST,OPTIONS,PUT,DELETE,PATCH',
  maxAge: 86400,
});
```

FYI, I am using `http-proxy-middleware`, so all my requests are being forwarded to another backend. I am sorry that I really don't have time to provide an example to reproduce this.

**Comment by jsumners** [comment]
> I am sorry that I really don't have time to provide an example to reproduce this.

Then how can you expect others to find the time to investigate your issue?

**Comment by tuanalumi** [comment]
You're right. I didn't expect so either.

For now I am using cors package, and it works for me.

I just thought that it would be good if I report this problem to this
plugin, like, someone with better experience with fastify-cors will know
where the problem is.

I will provide a full example to reproduce later.

**Comment by chaitanya-apty** [comment]
Hello,
These are my cors options with fastify-cors
It works with all kinds of requests with perfect cors headers attached to all requests
Checked in :Chrome,Edge
My app details
Frontend :Port 3000
Server :Port 5000
const corsOptions = {
    origin: (origin: string, cb: corsCallback): unknown => {
        if (/localhost/.test(origin) || !origin) {
            //  Request from localhost will pass
            cb(null, true);
            return;
        }
        cb(new Error("Not Allowed By Cors"), false);
    },
    preflight: true,
    preflightContinue: true,
    maxAge: 86400,
    methods: ['GET', 'PUT', 'POST', 'DELETE']
};
