### ISSUE TITLE
TypeScript error

### ISSUE THREAD

**Issue by karianpour** [fastify/fastify-cors#78]
## 🐛 Bug Report

The type definition has some problem

## To Reproduce
The following does not give ant type problem, but does not work
```ts
import fastifyCors from 'fastify-cors';
console.log(fastifyCors); // shows undefined
fastifyServer.register(fastifyCors);
```
the following works but I had to get rid of type by using `as any`
```ts
import * as fastifyCors from 'fastify-cors';
fastifyServer.register(fastifyCors as any);

```

- *node version: 12
- *fastify version: >=3.0.0
- *os*: Linux

**Comment by mcollina** [comment]
@fox1t @Ethan-Arrowood can you take a look?

**Comment by fox1t** [comment]
I just check index.js and there is no .default on the module.exports, even if index.d.ts has export default.

**Comment by Ethan-Arrowood** [comment]
@fox1t would you like to send a PR updating the export? I think that is the only fix necessary

**Comment by fox1t** [comment]
This issue is fixed thanks to the new version of `fastify-plugin`.
