### ISSUE TITLE
Fastify-cors with middleware

### ISSUE THREAD

**Issue by Puena** [fastify/fastify-cors#8]
Q: If i use this plugin with session (express-session) middleware. I get session-cookie on prefligth response. I think it because used 'preHandler' hook that higher in lifecycle. It is true and i must use another express-like middleware cors or i have solution to use fastify-cors and express-session middleware together? Sorry if is it inappropriate question i am new in programming, i am just curios.

**Comment by mcollina** [comment]
I don't think you should be using express-session with this module.

Have you tried https://github.com/mcollina/fastify-secure-session?

**Comment by Puena** [comment]
ok i understood thank you for response and work on fastify.
