### ISSUE TITLE
post will CORS

### ISSUE THREAD

**Issue by l02162010** [fastify/fastify-cors#9]
fastify.register(require('fastify-cors'), {
  'origin': true,
  'methods': "GET,HEAD,PUT,PATCH,POST,DELETE"
})
<img width="792" alt="2018-12-17 11 56 08" src="https://user-images.githubusercontent.com/14830189/50098676-5b60ed80-0257-11e9-8245-37150011d219.png">

I set Schema 
<img width="514" alt="2018-12-17 11 48 32" src="https://user-images.githubusercontent.com/14830189/50098196-69fad500-0256-11e9-8ec0-04fff9e6a689.png">

if post don't follow Schema, it will console 

Access to XMLHttpRequest at 'http://localhost:4000/api/users' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
commons.app.js:697 Uncaught (in promise) Error: Network Error
<img width="640" alt="2018-12-17 11 50 29" src="https://user-images.githubusercontent.com/14830189/50098560-281e5e80-0257-11e9-98fb-0aecb4308dc0.png">
<img width="523" alt="2018-12-17 11 50 39" src="https://user-images.githubusercontent.com/14830189/50098575-2c4a7c00-0257-11e9-99d4-c76368361a03.png">

but if follow Schema, it will be fine.
<img width="700" alt="2018-12-17 11 50 46" src="https://user-images.githubusercontent.com/14830189/50098594-353b4d80-0257-11e9-9d06-5e612c1c8ee8.png">

so, how can I let error show up ?

**Comment by mcollina** [comment]
Can you please upload a full example and clear instructions on how to reproduce?

**Comment by l02162010** [comment]
1. git clone frontEnd & backEnd , and npm install
2. use `npm run dev` to run frontEnd & backEnd 
3. open http://localhost:3000/login
4. you will see the form, please input something and send
5. console will say cors problem
6. use editor open frontEnd
7. find /pages/login.vue in frontEnd folder
8. `confirmPwd: this.form.confirmPwd` open this
9. send  register again on http://localhost:3000/login
10. you will find it fine.

the step 5 , how to make it response like this
`
{
"statusCode": 400,
"error": "Bad Request",
"message": "body should have required property 'confirmPwd'"
}
`

**Comment by mcollina** [comment]
The error you are experiencing is totally normal. Basically you'll need to either:

a. serve your Nuxt app from within fastify itself
b. disable cors in development, so that it does not error
c. configure cors so that `localhost:4000` is allowed to send a request to `localhost:3000`

**Comment by l02162010** [comment]
I use [this](https://github.com/fastify/fastify/issues/326) solve my problem, thank you.
